apiVersion: v1
kind: Namespace
metadata:
  name: event-service
  labels:
    name: event-service

---

apiVersion: v1
kind: Endpoints
metadata:
  name: mysql
  namespace: event-service
  labels:
    endpoints: mysql
subsets:
  - addresses:
      - ip: 10.10.10.43
    ports:
      - port: 3306

---

apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: event-service
  labels:
    service: mysql
spec:
  ports:
    - port: 3306

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-service
  namespace: event-service
  labels:
    deployment: event-service
spec:
  minReadySeconds: 20
  replicas: 3
  selector:
    matchLabels:
      app: event-service
  strategy:
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 30%
    type: RollingUpdate
  template:
    metadata:
      name: event-service
      labels:
        app: event-service
    spec:
      containers:
        - image: fspub/event_service:latest
          imagePullPolicy: Always
          name: event-service
          env:
            - name: CONFIG_FILE_PATH
              value: /app/bin/config/config.json
          ports:
            - containerPort: 30070
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /app/bin/config
              name: config
            - mountPath: /app/bin/plugins
              name: plugins
            - mountPath: /app/bin/instances
              name: instances
            - mountPath: /etc/localtime
              name: localtime
      volumes:
        - name: config
          nfs:
            server: 10.10.10.221
            path: /home/yf-k8s-master/nfs/event_service/
        - name: plugins
          hostPath:
            path: /opt/plugins
        - name: instances
          hostPath:
            path: /opt/instances
        - name: localtime
          hostPath:
            path: /etc/localtime
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: event-service
  namespace: event-service
  labels:
    service: event-service
spec:
  type: NodePort
  selector:
    app: event-service
  ports:
    - port: 30070
      name: http
      protocol: TCP
      targetPort: http
      nodePort: 30070
